### PR TITLE
Changed references of "Pan-n-Scan" to "Pan&Scan" for consistency.

### PR DESCRIPTION
**Pull request by cunnj**
Also fixed incorrect capitalization of "to".

### CODE REVIEW

**Comment by XhmikosR** [comment]
@kasper93: this needs to be merged manually if you agree.

Also, I don't get the degree change; the characters look identical to me.

**Comment by johnc7995** [comment]
I didn't change the degree symbol, at least not voluntarily.

**Comment by XhmikosR** [comment]
Can you make the changes again with a proper code editor?

**Comment by kasper93** [comment]
Looks ok. I will merge it with next translation update. Of course with fixed encoding.

**Comment by matthewmauger** [comment]
Looks fine, though the degree thing is weird.

@XhmikosR - why does this need a manual merge?

**Comment by XhmikosR** [comment]
@matthewmauger: the resources need to be updated too :)

The scripts are here https://github.com/mpc-hc/mpc-hc/tree/develop/src/mpc-hc/mpcresources

Basically needs https://github.com/mpc-hc/mpc-hc/blob/develop/src/mpc-hc/mpcresources/UpdateIS.bat after this patch is merged so that the translations pick up the changes.

We use Transifex for translations BTW.

**Comment by matthewmauger** [comment]
@XhmikosR: Ah, understood. Forgive my ignorance but should we approve, let the change get pushed, manually pull develop, fix the resources and push back the adjusted resource files?

I'll approve this change then but I don't think I currently have the rights to do anything more than that.

**Review by matthewmauger — APPROVED** [review]
Approved, looks fine and sounds like the resource update is a separate step that needs to be done after your changes are in.

**Comment by XhmikosR** [comment]
Yeah but since the encoding changes aren't made you shouldn't approve it.

**Review by matthewmauger — CHANGES_REQUESTED** [review]
Sure, waiting for translation changes as requested.

@XhmikosR, you'll have to explain to me exactly when those translation changes get merged in - are you expecting the original author to do it or someone with write access to develop?

**Comment by XhmikosR** [comment]
I tried to manually merge this but then all translations for those strings will be reset so I'm not sure if it's worth the change. Alternatively we could do a search and replace manually.

**Comment by kasper93** [comment]
Thanks!

**Comment by blackarcher21** [comment]
for Pan&Scan,  I just recheck latest nighlty (1.7.13.60) it become acceleration key instead of showing the "&" character.

**Pull request closed without merging**
