### PR TITLE
Repeat mode control

### PR DESCRIPTION
**Pull request by montoner0**
Hi,
I've added the ability to change repeat mode through menus\hot-keys and new repeat mode - repeat one file.
options
options2
menu

Best regards.

### CODE REVIEW

**Comment by kasper93** [comment]
Merged as 1769ec20a02f312b9e35193a97329ade5313b826, Thanks!

**Comment by evandrocoan** [comment]
1. What `Repeat forever or Play` + `Repeat mode: Playlist or File` does?
1. If I use (x) Play, then, the option `Repeat mode: Playlist or File` is ignored?
1. What does mean use the option `Repeat mode: Playlist` or `Repeat mode: File`?

image

**Comment by montoner0** [comment]
@evandrocoan This option controls how playback will work. Repeat file or playlist N times or indefinitely. Repeat mode is valid for every option.

**Comment by evandrocoan** [comment]
What is the difference between selection `Repeat Mode: File` or `Repeat Mode: File`?
1. `Repeat Mode: File` will always repeat the current file?
1. `Repeat Mode: Playlist` will always repeat the playlist?

If I select `[x] Play 1 time(s)` what `Repeat Mode: File` will do? It will be a ignored setting?

**Comment by montoner0** [comment]
They do literally what they say. Repeat mode controls repeating of file or playlist, regardless finite or infinite. Play N times will play file or playlist N times. If N == 1 it will play 1 time and then stop.

**Pull request closed without merging**
