### PR TITLE
Fix initialize order

### PR DESCRIPTION
**Pull request by Chocobo1**
cppcheck found a lot other warnings but most of them are just noise...

### CODE REVIEW

**Comment by XhmikosR** [comment]
@Chocobo1: are these the only ones?

**Comment by Chocobo1** [comment]
Yes, the PR is ready.

**Comment by XhmikosR** [comment]
Weird I'd expect us to have more issues like that in the code base.

**Comment by XhmikosR** [comment]
@Chocobo1: thanks, I [cherry picked](https://github.com/XhmikosR/mpc-hc/commit/75cfdc824cb27414da0f5175d81e1a5310d85adb) it in my fork and I'll push with the next batch of patches.

**Pull request closed without merging**
