### PR TITLE
Rewrite subtitles downloading framework

### PR DESCRIPTION
**Pull request by ioannis-e**
The scope of this project is to rewrite the subtitles downloading framework, in order to:
- be able to support more subtitles providers both with or without an API.
- limit requested subtitles to selected languages only instead of flooding the table with unwanted languages. 
- prioritize subtitles for hearing impaired where indicated
- provide a framework to automatically search and download subtitles at the beginning of playback without user interaction by ranking the subtitles served by each provider, based on file name information, hearing impaired and language.
- finally provide a framework to enable subtitles uploads to providers.

_Auto download feature specification_
```
All providers start searching simultaneusly and are allowed to download subtitles by order of completion.
If no langauages are selected in the language filter then the dialogbox appears and user can manually select a subtitle.
if languages are selected, then subtitles will be automatically downloaded based on priority, ie.
if none of the subtitles found have an adequate internal score, the dowload window is shown.
SCENARIO 1
if user has selected "ell,eng" then,
if the first porvider that completes the search only serves "eng" it is entitled to download and activate "eng".
if the second provider that completes the serach serves "eng" and "ell" it is entitled to download and activate only "ell" which has a higher priority.
The third etc providers will not be entitled to download or activate any subtitles as the highest priority language has been served.
SCENARIO 2
if user has selected "ell,eng" then,
if the first porvider that completes the search serves both "ell" and "eng" it is entitled to download and activate only "ell", which has a higher priority.
The second etc providers to complete are not entitled to download or activate any subtitles as the highest priority language has been served.
```
_Status of project:_
- [x] implement framework to support subtitles providers both with or without an API.
- [x] migrate OpenSubtitles ISDB protocol to XML-RPC protocol which supports uploads.
- [x] implement uploading to OpenSubtitles
- [x] implement search/download/upload support for SubDB (http://thesubdb.com/api/)
- [x] limit requested subtitles to selected languages only instead of flooding the table with unwanted languages. 
- [x] prioritize subtitles for hearing impaired where indicated
- [x] automatically search and download subtitles at the beginning of playback without user interaction if nonre are embedded or found locally
- [x] UI settings to enable/disable subtitles providers and show info about each provider
- [x] Resolve multi-threading issues
- [x] Remember download dialog sort column and show sorting arrow on header columns
- [x] Default sorting by language preference then by hearing impaired preference, then by internal score
- [x] Improve ranking of subtitles served by each provider, based on file name information, hearing impaired and language ensures that only one subtitle is downloaded per higher priority language.
- [ ] Internationalization/translation for new strings
- [ ] podnapisi special episodes may not be detected/searched correctly
- [x] Add favicons for each provider

*Current state of implementations:*

| Provider  | Type | Search & Download  | Upload | Login |
| :------------ | :---------------: | :-----: | :---------------: | :-----: |
| OpenSubtitles | API, hash    | Y | Y | Y |
| SubDB | API, hash | Y | Y | N/A |
| podnapisi | XML | Y | N | N |
| TVSubtitles | HTML | Y | N | N |
| MovieSubtitles | HTML | Y | N | N |
| addic7ed | HTML | Y | N | Y |
| titlovi (WIP) | XML | Y | N | N |

_Issues:_
- [ ] Issue with implementation of _regex_ library regarding repeated alternation
http://connect.microsoft.com/VisualStudio/feedback/details/812645/regex-repeated-alternation

_Visual aid:_

Options
image

Download
image

Upload
image

Context menu
image

Dependencies included in PR:
- [x] TimXmlRpc (http://sourceforge.net/projects/xmlrpcc4win/)
- [x] minizip (part of zlib)

Builds for test purposes - v1.7.7.24 (7572a20):

x86: https://drive.google.com/file/d/0B_jV1CFl8NWlTlBub0lmV2xuWVU/edit?usp=sharing
x64: https://drive.google.com/file/d/0B_jV1CFl8NWlV3ZlSjFpUmZsbm8/edit?usp=sharing

### CODE REVIEW

**Comment by jrhames** [comment]
@kasper93 Can't you integrate this as it is for now, and then work on migrating this into a scripted modular fashion like you've suggested? Think of all the work done by @ioannis-e over the past year. Do you really want to have this feature delayed even more?

**Comment by kasper93** [comment]
To be honest modular design is just a suggestion. And since it probably would probably require massive redesign it might be reasonable to decide about it before taking further steps. 

But I don't consider this as a blocker. We need to find common ground about the changes. I recall that others had complains about html parsers being hard coded. And that's other issues too. 

And since I spoke I will try to take a closer look at this PR this weekend and post my thoughts about it.

@mpc-hc/developers Is it possible to resurrect this PR? Can we talk about it?

**Comment by Underground78** [comment]
> Is it possible to resurrect this PR? Can we talk about it?

Sure but that's certainly not for this stable (not that I think you actually wanted that). First I think a great start would be to do a bit of clean up in the commits (and possibly the code if there are obvious things).

**Comment by kasper93** [comment]
> Sure but that's certainly not for this stable (not that I think you actually wanted that).

You made my day :) Sure I don't want it for this stable. 

> First I think a great start would be to do a bit of clean up in the commits (and possibly the code if there are obvious things).

I agree also removing or commenting out controversial parsers might be also good start. IIRC addic7ed owners haven't really agreed on parser. @ioannis-e Like U78 said I think if you manage to clean up form unrelated changes like MSYS and others. I think it will help us to move forward. We need to make this first step somehow. There will always be room for improvements and enchantments.

**Comment by alexmarsev** [comment]
The only thing I really didn't like about this PR was the presence of hardcoded site parsers, which could stop working anytime. That's where the suggestion of injectable providers with separate update scheme from the main mpc-hc came from.

**Comment by Underground78** [comment]
> You made my day :) Sure I don't want it for this stable.

That was mostly for whoever could be following this PR. ;)

**Comment by jrhames** [comment]
@alexmarsev I agree injectable providers would be the way to go, but, like before mentioned, migrating to it would take a huge amount of time. I like @kasper93 suggestion of removing "non-approved parsers/website scrappers" for now, to avoid problems. We can bring back the scrappers once we have a way to update/distribute them separately.

**Comment by alexmarsev** [comment]
I'm all for merging this asap without "non-approved parsers/website scrappers", actually. But we need to hear from @ioannis-e about his plans.

**Comment by ioannis-e** [comment]
@mpc-hc/developers
Well my plans initially included porting the subtitles providers code to lua, but I currently don't have time to do it, due to work (any help on that would be appreciated).

What I can do (probably over the weekend) is transfer all subtitles providers code to extrernally loadable dll's (one per provider) from a "Plugins" folder and use git submodules to connect the code to the mpc-hc solution.

Therefore devs can include any providers they want in the official distro (by using submodules), and any additional providers can be included manually by the user by placing the relevant dll in the "Plugins" folder, that can be distributed from my own git repos...

How do you feel about this solution ?

**Comment by alexmarsev** [comment]
@ioannis-e
I think it can be done, as long as:
1. All providers that have official APIs will go into mpc-hc.exe (no additional DLLs). Basically this PR without some providers, no need for any new submodules. Everybody already more or less agreed to it above.
2. Additional providers will go into separate pull request. Or rather not providers themselves, but an ability to (auto)load them.
3. About that new pull request. One important thing - we need to be the ones doing the build process of any additional providers, for security reasons. Other concerns are minor and can be resolved quickly inside that new pull request.

@kasper93, @Underground78, @XhmikosR
Do you agree to it?

**Comment by Underground78** [comment]
Seems like sensible to me.

**Comment by kasper93** [comment]
Sorry... I hit button accidentally. 

Yes, I can agree on that. But I think precompiled dlls will be less convenient than scripts. At least if user want to hack around. Scripts generally are easy to work with due to lack of compilation process. And could be freely shared by our user base as opposed to dlls which should never be shipped by anyone but us. 

I could probably help with this in February if you want, I won't have time before.

**Comment by ioannis-e** [comment]
Removed HTML parsers
Fixed some api updates for OS
Fixed podnapisi parsing as XML instead of regex to be more robust
Removed irrelevant commits

So hopefully everybody is happy now... ;)

**Comment by XhmikosR** [comment]
@ioannis-e: something is definitely wrong; try rebasing again and skip the upstream patches. You will also need to make a new PR since you can't change the target branches otherwise.

**Comment by ioannis-e** [comment]
Wow... you are right, probably mixup with branches.

Ok so i'll close this PR and we pick it up in new one.

**Comment by XhmikosR** [comment]
Yeah, unfortunately it's one of GitHub's limitations :/

Anyway, please keep as many info from this OP as possible, since it's very detailed.

**Pull request closed without merging**
