### PR TITLE
VSFilter timestamp longlong

### PR DESCRIPTION
**Pull request by slydiman**
I have tested with these 2 commits and it works fine.

### CODE REVIEW

**Comment by Underground78** [comment]
I don't really see the point of this. int is enough to have more than 500h with a ms precision.

**Comment by slydiman** [comment]
We have discussed it yesterday in IRC. I'm trying to use VSFilter in the StreamBufferEngine with absolute timestamps. This SBE uses the filetime format for timestamps (same 100ns units as reference time). So I got really huge numbers which are totally corrupted inside VSFilter. Everything works fine with SBE after these fixes.

**Comment by kasper93** [comment]
> I don't really see the point of this. int is enough to have more than 500h with a ms precision.

Eh, I said exactly that on IRC yesterday. :) But if it is needed I'm fine with changing that.

@slydiman: Please use `REFERENCE_TIME` type instead of `LONGLONG`. Also if you are changing those types you need to change everything related. Also I wouldn't convert times to milliseconds anymore if we use bigger data type. Rater use RT everywhere.

**Comment by slydiman** [comment]
I used LONGLONG instead of REFERENCE_TIME because of milliseconds. 
Ok, I will update it to RT and no milliseconds anymore.

**Comment by slydiman** [comment]
Complete

**Comment by slydiman** [comment]
Just wondering... Has anyone had a chance to review it? Thanks.

**Pull request closed without merging**
