### PR TITLE
Added Transifex link

### PR DESCRIPTION
**Pull request by Conder000**
* Added link to Transifex
* Minor edits

### CODE REVIEW

**Comment by kasper93** [comment]
Can you also sync this changes in docs/Readme.txt?

**Comment by XhmikosR** [comment]
Please remove the edit for the OS. It's redundant now. Or perhaps edit it
to say support for modern Windows versions or something. Otherwise just
remove the edit

**Comment by Conder000** [comment]
New commit. Is it OK?

**Comment by kasper93** [comment]
Looks ok for me, thanks. @XhmikosR  if you agree with the changes, please merge it.

**Pull request merged**
